// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: city_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCityStats = `-- name: CreateCityStats :one
INSERT INTO city_stats (
    user_id, name, state, country, population, area
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, name, state, country, population, area, total_streets_walked, total_kilometers, city_coverage_pct, days_active, longest_streak_days, created_at, updated_at
`

type CreateCityStatsParams struct {
	UserID     string         `json:"user_id"`
	Name       string         `json:"name"`
	State      string         `json:"state"`
	Country    string         `json:"country"`
	Population pgtype.Int4    `json:"population"`
	Area       pgtype.Numeric `json:"area"`
}

func (q *Queries) CreateCityStats(ctx context.Context, arg CreateCityStatsParams) (CityStat, error) {
	row := q.db.QueryRow(ctx, createCityStats,
		arg.UserID,
		arg.Name,
		arg.State,
		arg.Country,
		arg.Population,
		arg.Area,
	)
	var i CityStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.Country,
		&i.Population,
		&i.Area,
		&i.TotalStreetsWalked,
		&i.TotalKilometers,
		&i.CityCoveragePct,
		&i.DaysActive,
		&i.LongestStreakDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCityStats = `-- name: GetUserCityStats :one

SELECT id, user_id, name, state, country, population, area, total_streets_walked, total_kilometers, city_coverage_pct, days_active, longest_streak_days, created_at, updated_at FROM city_stats WHERE user_id = $1
`

// sql/queries/city_stats.sql
func (q *Queries) GetUserCityStats(ctx context.Context, userID string) (CityStat, error) {
	row := q.db.QueryRow(ctx, getUserCityStats, userID)
	var i CityStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.Country,
		&i.Population,
		&i.Area,
		&i.TotalStreetsWalked,
		&i.TotalKilometers,
		&i.CityCoveragePct,
		&i.DaysActive,
		&i.LongestStreakDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCityStats = `-- name: UpdateCityStats :one
UPDATE city_stats 
SET 
    total_streets_walked = COALESCE($2, total_streets_walked),
    total_kilometers = COALESCE($3, total_kilometers),
    city_coverage_pct = COALESCE($4, city_coverage_pct),
    days_active = COALESCE($5, days_active),
    longest_streak_days = COALESCE($6, longest_streak_days),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, name, state, country, population, area, total_streets_walked, total_kilometers, city_coverage_pct, days_active, longest_streak_days, created_at, updated_at
`

type UpdateCityStatsParams struct {
	UserID             string         `json:"user_id"`
	TotalStreetsWalked pgtype.Int4    `json:"total_streets_walked"`
	TotalKilometers    pgtype.Numeric `json:"total_kilometers"`
	CityCoveragePct    pgtype.Numeric `json:"city_coverage_pct"`
	DaysActive         pgtype.Int4    `json:"days_active"`
	LongestStreakDays  pgtype.Int4    `json:"longest_streak_days"`
}

func (q *Queries) UpdateCityStats(ctx context.Context, arg UpdateCityStatsParams) (CityStat, error) {
	row := q.db.QueryRow(ctx, updateCityStats,
		arg.UserID,
		arg.TotalStreetsWalked,
		arg.TotalKilometers,
		arg.CityCoveragePct,
		arg.DaysActive,
		arg.LongestStreakDays,
	)
	var i CityStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.Country,
		&i.Population,
		&i.Area,
		&i.TotalStreetsWalked,
		&i.TotalKilometers,
		&i.CityCoveragePct,
		&i.DaysActive,
		&i.LongestStreakDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
