// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friends.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkFriendshipExists = `-- name: CheckFriendshipExists :one
SELECT COUNT(*) FROM user_friends 
WHERE user_id = $1 AND friend_id = $2
`

type CheckFriendshipExistsParams struct {
	UserID   string `json:"user_id"`
	FriendID string `json:"friend_id"`
}

func (q *Queries) CheckFriendshipExists(ctx context.Context, arg CheckFriendshipExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkFriendshipExists, arg.UserID, arg.FriendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFriend = `-- name: CreateFriend :one
INSERT INTO user_friends (
    user_id, friend_id, user_name, first_name, last_name, image_url
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, friend_id, user_name, first_name, last_name, image_url, created_at
`

type CreateFriendParams struct {
	UserID    string      `json:"user_id"`
	FriendID  string      `json:"friend_id"`
	UserName  string      `json:"user_name"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	ImageUrl  pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateFriend(ctx context.Context, arg CreateFriendParams) (UserFriend, error) {
	row := q.db.QueryRow(ctx, createFriend,
		arg.UserID,
		arg.FriendID,
		arg.UserName,
		arg.FirstName,
		arg.LastName,
		arg.ImageUrl,
	)
	var i UserFriend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.UserName,
		&i.FirstName,
		&i.LastName,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFriend = `-- name: DeleteFriend :exec
DELETE FROM user_friends 
WHERE user_id = $1 AND friend_id = $2
`

type DeleteFriendParams struct {
	UserID   string `json:"user_id"`
	FriendID string `json:"friend_id"`
}

func (q *Queries) DeleteFriend(ctx context.Context, arg DeleteFriendParams) error {
	_, err := q.db.Exec(ctx, deleteFriend, arg.UserID, arg.FriendID)
	return err
}

const getMutualFriends = `-- name: GetMutualFriends :many
SELECT DISTINCT f1.friend_id as mutual_friend_id
FROM user_friends f1
JOIN user_friends f2 ON f1.friend_id = f2.friend_id
WHERE f1.user_id = $1 AND f2.user_id = $2
`

type GetMutualFriendsParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

func (q *Queries) GetMutualFriends(ctx context.Context, arg GetMutualFriendsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getMutualFriends, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mutual_friend_id string
		if err := rows.Scan(&mutual_friend_id); err != nil {
			return nil, err
		}
		items = append(items, mutual_friend_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFriends = `-- name: GetUserFriends :many

SELECT 
    uf.id,
    uf.friend_id,
    uf.user_name,
    uf.first_name,
    uf.last_name,
    uf.image_url,
    uf.created_at
FROM user_friends uf
WHERE uf.user_id = $1
ORDER BY uf.created_at DESC
`

type GetUserFriendsRow struct {
	ID        string             `json:"id"`
	FriendID  string             `json:"friend_id"`
	UserName  string             `json:"user_name"`
	FirstName pgtype.Text        `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// sql/queries/friends.sql
func (q *Queries) GetUserFriends(ctx context.Context, userID string) ([]GetUserFriendsRow, error) {
	rows, err := q.db.Query(ctx, getUserFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFriendsRow
	for rows.Next() {
		var i GetUserFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendID,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
