// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Language string

const (
	LanguageEn Language = "En"
	LanguageEs Language = "Es"
	LanguageFr Language = "Fr"
	LanguageDe Language = "De"
	LanguageZh Language = "Zh"
	LanguageJa Language = "Ja"
	LanguageRu Language = "Ru"
	LanguageBg Language = "Bg"
)

func (e *Language) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Language(s)
	case string:
		*e = Language(s)
	default:
		return fmt.Errorf("unsupported scan type for Language: %T", src)
	}
	return nil
}

type NullLanguage struct {
	Language Language `json:"language"`
	Valid    bool     `json:"valid"` // Valid is true if Language is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.Language, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Language.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Language), nil
}

type MessagesAllowance string

const (
	MessagesAllowanceALLMSG    MessagesAllowance = "ALLMSG"
	MessagesAllowanceUNREADMAS MessagesAllowance = "UNREADMAS"
	MessagesAllowanceHIDE      MessagesAllowance = "HIDE"
)

func (e *MessagesAllowance) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesAllowance(s)
	case string:
		*e = MessagesAllowance(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesAllowance: %T", src)
	}
	return nil
}

type NullMessagesAllowance struct {
	MessagesAllowance MessagesAllowance `json:"messages_allowance"`
	Valid             bool              `json:"valid"` // Valid is true if MessagesAllowance is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesAllowance) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesAllowance, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesAllowance.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesAllowance) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesAllowance), nil
}

type Motion string

const (
	MotionREDUCEDMOTION               Motion = "REDUCEDMOTION"
	MotionSYNCWITHDEVICE              Motion = "SYNCWITHDEVICE"
	MotionDONTPLAYGIFWHENPOSSIBLESHOW Motion = "DONTPLAYGIFWHENPOSSIBLESHOW"
	MotionPLAYEMOJIES                 Motion = "PLAYEMOJIES"
)

func (e *Motion) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Motion(s)
	case string:
		*e = Motion(s)
	default:
		return fmt.Errorf("unsupported scan type for Motion: %T", src)
	}
	return nil
}

type NullMotion struct {
	Motion Motion `json:"motion"`
	Valid  bool   `json:"valid"` // Valid is true if Motion is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMotion) Scan(value interface{}) error {
	if value == nil {
		ns.Motion, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Motion.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMotion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Motion), nil
}

type RoleColors string

const (
	RoleColorsNEXTTONAME        RoleColors = "NEXTTONAME"
	RoleColorsINNAME            RoleColors = "INNAME"
	RoleColorsDONTSHOW          RoleColors = "DONTSHOW"
	RoleColorsSYNCPROFILECOLORS RoleColors = "SYNCPROFILECOLORS"
)

func (e *RoleColors) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleColors(s)
	case string:
		*e = RoleColors(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleColors: %T", src)
	}
	return nil
}

type NullRoleColors struct {
	RoleColors RoleColors `json:"role_colors"`
	Valid      bool       `json:"valid"` // Valid is true if RoleColors is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleColors) Scan(value interface{}) error {
	if value == nil {
		ns.RoleColors, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleColors.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleColors) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleColors), nil
}

type StickersAnimation string

const (
	StickersAnimationALWAYS        StickersAnimation = "ALWAYS"
	StickersAnimationONINTERACTION StickersAnimation = "ONINTERACTION"
	StickersAnimationNEVER         StickersAnimation = "NEVER"
)

func (e *StickersAnimation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StickersAnimation(s)
	case string:
		*e = StickersAnimation(s)
	default:
		return fmt.Errorf("unsupported scan type for StickersAnimation: %T", src)
	}
	return nil
}

type NullStickersAnimation struct {
	StickersAnimation StickersAnimation `json:"stickers_animation"`
	Valid             bool              `json:"valid"` // Valid is true if StickersAnimation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStickersAnimation) Scan(value interface{}) error {
	if value == nil {
		ns.StickersAnimation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StickersAnimation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStickersAnimation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StickersAnimation), nil
}

type TextSize string

const (
	TextSizeBIG    TextSize = "BIG"
	TextSizeMEDIUM TextSize = "MEDIUM"
	TextSizeSMALL  TextSize = "SMALL"
)

func (e *TextSize) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TextSize(s)
	case string:
		*e = TextSize(s)
	default:
		return fmt.Errorf("unsupported scan type for TextSize: %T", src)
	}
	return nil
}

type NullTextSize struct {
	TextSize TextSize `json:"text_size"`
	Valid    bool     `json:"valid"` // Valid is true if TextSize is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTextSize) Scan(value interface{}) error {
	if value == nil {
		ns.TextSize, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TextSize.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTextSize) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TextSize), nil
}

type Theme string

const (
	ThemeLIGHT  Theme = "LIGHT"
	ThemeDARK   Theme = "DARK"
	ThemeSYSTEM Theme = "SYSTEM"
)

func (e *Theme) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Theme(s)
	case string:
		*e = Theme(s)
	default:
		return fmt.Errorf("unsupported scan type for Theme: %T", src)
	}
	return nil
}

type NullTheme struct {
	Theme Theme `json:"theme"`
	Valid bool  `json:"valid"` // Valid is true if Theme is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTheme) Scan(value interface{}) error {
	if value == nil {
		ns.Theme, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Theme.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTheme) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Theme), nil
}

type UserRole string

const (
	UserRoleUSER      UserRole = "USER"
	UserRoleADMIN     UserRole = "ADMIN"
	UserRoleMODERATOR UserRole = "MODERATOR"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSLEEP     UserStatus = "SLEEP"
	UserStatusOFFLINE   UserStatus = "OFFLINE"
	UserStatusBANNED    UserStatus = "BANNED"
	UserStatusPENDING   UserStatus = "PENDING"
	UserStatusIDLE      UserStatus = "IDLE"
	UserStatusINVISIBLE UserStatus = "INVISIBLE"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type CityStat struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	Name               string             `json:"name"`
	State              string             `json:"state"`
	Country            string             `json:"country"`
	Population         pgtype.Int4        `json:"population"`
	Area               pgtype.Numeric     `json:"area"`
	TotalStreetsWalked pgtype.Int4        `json:"total_streets_walked"`
	TotalKilometers    pgtype.Numeric     `json:"total_kilometers"`
	CityCoveragePct    pgtype.Numeric     `json:"city_coverage_pct"`
	DaysActive         pgtype.Int4        `json:"days_active"`
	LongestStreakDays  pgtype.Int4        `json:"longest_streak_days"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	Name         string             `json:"name"`
	Location     string             `json:"location"`
	LastLoggedIn pgtype.Timestamptz `json:"last_logged_in"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	ID                               string                `json:"id"`
	UserID                           string                `json:"user_id"`
	Theme                            NullTheme             `json:"theme"`
	Language                         NullLanguage          `json:"language"`
	TextSize                         NullTextSize          `json:"text_size"`
	ZoomLevel                        pgtype.Text           `json:"zoom_level"`
	FontStyle                        pgtype.Text           `json:"font_style"`
	MessagesAllowance                NullMessagesAllowance `json:"messages_allowance"`
	ShowRoleColors                   NullRoleColors        `json:"show_role_colors"`
	Motion                           NullMotion            `json:"motion"`
	StickersAnimation                NullStickersAnimation `json:"stickers_animation"`
	EnabledLocationTracking          pgtype.Bool           `json:"enabled_location_tracking"`
	AllowCityStatDataUsage           pgtype.Bool           `json:"allow_city_stat_data_usage"`
	AllowDataPersonalizationUsage    pgtype.Bool           `json:"allow_data_personalization_usage"`
	AllowInAppRewards                pgtype.Bool           `json:"allow_in_app_rewards"`
	AllowDataAnalyticsAndPerformance pgtype.Bool           `json:"allow_data_analytics_and_performance"`
	EnableInAppNotifications         pgtype.Bool           `json:"enable_in_app_notifications"`
	EnableSoundEffects               pgtype.Bool           `json:"enable_sound_effects"`
	EnableVibration                  pgtype.Bool           `json:"enable_vibration"`
	CreatedAt                        pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt                        pgtype.Timestamptz    `json:"updated_at"`
}

type StreetWalk struct {
	ID         string             `json:"id"`
	CityStatID string             `json:"city_stat_id"`
	StreetName string             `json:"street_name"`
	GeoJson    []byte             `json:"geo_json"`
	DistanceKm pgtype.Numeric     `json:"distance_km"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                string             `json:"id"`
	Email             string             `json:"email"`
	FirstName         pgtype.Text        `json:"first_name"`
	LastName          pgtype.Text        `json:"last_name"`
	UserName          pgtype.Text        `json:"user_name"`
	ImageUrl          pgtype.Text        `json:"image_url"`
	PhoneNumber       pgtype.Text        `json:"phone_number"`
	Role              NullUserRole       `json:"role"`
	Status            NullUserStatus     `json:"status"`
	CompletedTutorial pgtype.Bool        `json:"completed_tutorial"`
	AboutMe           pgtype.Text        `json:"about_me"`
	Note              pgtype.Text        `json:"note"`
	DisableAccount    pgtype.Bool        `json:"disable_account"`
	DeleteAccount     pgtype.Bool        `json:"delete_account"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserFriend struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	FriendID  string             `json:"friend_id"`
	UserName  string             `json:"user_name"`
	FirstName pgtype.Text        `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VisitedStreet struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	SessionID       string             `json:"session_id"`
	StreetID        string             `json:"street_id"`
	StreetName      string             `json:"street_name"`
	EntryTimestamp  int64              `json:"entry_timestamp"`
	ExitTimestamp   pgtype.Int8        `json:"exit_timestamp"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	EntryLatitude   pgtype.Numeric     `json:"entry_latitude"`
	EntryLongitude  pgtype.Numeric     `json:"entry_longitude"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
