// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckFriendshipExists(ctx context.Context, arg CheckFriendshipExistsParams) (int64, error)
	CheckVisitedStreetExists(ctx context.Context, arg CheckVisitedStreetExistsParams) (int64, error)
	CreateCityStats(ctx context.Context, arg CreateCityStatsParams) (CityStat, error)
	CreateFriend(ctx context.Context, arg CreateFriendParams) (UserFriend, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (Setting, error)
	CreateVisitedStreet(ctx context.Context, arg CreateVisitedStreetParams) (VisitedStreet, error)
	DeleteFriend(ctx context.Context, arg DeleteFriendParams) error
	DeleteUser(ctx context.Context, id string) error
	GetMutualFriends(ctx context.Context, arg GetMutualFriendsParams) ([]string, error)
	// sql/queries/users.sql
	GetUser(ctx context.Context, id string) (User, error)
	// sql/queries/city_stats.sql
	GetUserCityStats(ctx context.Context, userID string) (CityStat, error)
	// sql/queries/friends.sql
	GetUserFriends(ctx context.Context, userID string) ([]GetUserFriendsRow, error)
	// sql/queries/settings.sql
	GetUserSettings(ctx context.Context, userID string) (Setting, error)
	// sql/queries/visited_streets.sql
	GetVisitedStreets(ctx context.Context, userID string) ([]VisitedStreet, error)
	GetVisitedStreetsBySession(ctx context.Context, arg GetVisitedStreetsBySessionParams) ([]VisitedStreet, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	UpdateCityStats(ctx context.Context, arg UpdateCityStatsParams) (CityStat, error)
	UpdateLocationPermission(ctx context.Context, arg UpdateLocationPermissionParams) (pgtype.Bool, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (Setting, error)
}

var _ Querier = (*Queries)(nil)
