// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO settings (
    user_id, theme, language, text_size, zoom_level, font_style,
    messages_allowance, show_role_colors, motion, stickers_animation,
    enabled_location_tracking, allow_city_stat_data_usage,
    allow_data_personalization_usage, allow_in_app_rewards,
    allow_data_analytics_and_performance, enable_in_app_notifications,
    enable_sound_effects, enable_vibration
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, user_id, theme, language, text_size, zoom_level, font_style, messages_allowance, show_role_colors, motion, stickers_animation, enabled_location_tracking, allow_city_stat_data_usage, allow_data_personalization_usage, allow_in_app_rewards, allow_data_analytics_and_performance, enable_in_app_notifications, enable_sound_effects, enable_vibration, created_at, updated_at
`

type CreateUserSettingsParams struct {
	UserID                           string                `json:"user_id"`
	Theme                            NullTheme             `json:"theme"`
	Language                         NullLanguage          `json:"language"`
	TextSize                         NullTextSize          `json:"text_size"`
	ZoomLevel                        pgtype.Text           `json:"zoom_level"`
	FontStyle                        pgtype.Text           `json:"font_style"`
	MessagesAllowance                NullMessagesAllowance `json:"messages_allowance"`
	ShowRoleColors                   NullRoleColors        `json:"show_role_colors"`
	Motion                           NullMotion            `json:"motion"`
	StickersAnimation                NullStickersAnimation `json:"stickers_animation"`
	EnabledLocationTracking          pgtype.Bool           `json:"enabled_location_tracking"`
	AllowCityStatDataUsage           pgtype.Bool           `json:"allow_city_stat_data_usage"`
	AllowDataPersonalizationUsage    pgtype.Bool           `json:"allow_data_personalization_usage"`
	AllowInAppRewards                pgtype.Bool           `json:"allow_in_app_rewards"`
	AllowDataAnalyticsAndPerformance pgtype.Bool           `json:"allow_data_analytics_and_performance"`
	EnableInAppNotifications         pgtype.Bool           `json:"enable_in_app_notifications"`
	EnableSoundEffects               pgtype.Bool           `json:"enable_sound_effects"`
	EnableVibration                  pgtype.Bool           `json:"enable_vibration"`
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, createUserSettings,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.TextSize,
		arg.ZoomLevel,
		arg.FontStyle,
		arg.MessagesAllowance,
		arg.ShowRoleColors,
		arg.Motion,
		arg.StickersAnimation,
		arg.EnabledLocationTracking,
		arg.AllowCityStatDataUsage,
		arg.AllowDataPersonalizationUsage,
		arg.AllowInAppRewards,
		arg.AllowDataAnalyticsAndPerformance,
		arg.EnableInAppNotifications,
		arg.EnableSoundEffects,
		arg.EnableVibration,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.TextSize,
		&i.ZoomLevel,
		&i.FontStyle,
		&i.MessagesAllowance,
		&i.ShowRoleColors,
		&i.Motion,
		&i.StickersAnimation,
		&i.EnabledLocationTracking,
		&i.AllowCityStatDataUsage,
		&i.AllowDataPersonalizationUsage,
		&i.AllowInAppRewards,
		&i.AllowDataAnalyticsAndPerformance,
		&i.EnableInAppNotifications,
		&i.EnableSoundEffects,
		&i.EnableVibration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one

SELECT id, user_id, theme, language, text_size, zoom_level, font_style, messages_allowance, show_role_colors, motion, stickers_animation, enabled_location_tracking, allow_city_stat_data_usage, allow_data_personalization_usage, allow_in_app_rewards, allow_data_analytics_and_performance, enable_in_app_notifications, enable_sound_effects, enable_vibration, created_at, updated_at FROM settings WHERE user_id = $1
`

// sql/queries/settings.sql
func (q *Queries) GetUserSettings(ctx context.Context, userID string) (Setting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.TextSize,
		&i.ZoomLevel,
		&i.FontStyle,
		&i.MessagesAllowance,
		&i.ShowRoleColors,
		&i.Motion,
		&i.StickersAnimation,
		&i.EnabledLocationTracking,
		&i.AllowCityStatDataUsage,
		&i.AllowDataPersonalizationUsage,
		&i.AllowInAppRewards,
		&i.AllowDataAnalyticsAndPerformance,
		&i.EnableInAppNotifications,
		&i.EnableSoundEffects,
		&i.EnableVibration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocationPermission = `-- name: UpdateLocationPermission :one
UPDATE settings 
SET 
    enabled_location_tracking = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING enabled_location_tracking
`

type UpdateLocationPermissionParams struct {
	UserID                  string      `json:"user_id"`
	EnabledLocationTracking pgtype.Bool `json:"enabled_location_tracking"`
}

func (q *Queries) UpdateLocationPermission(ctx context.Context, arg UpdateLocationPermissionParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, updateLocationPermission, arg.UserID, arg.EnabledLocationTracking)
	var enabled_location_tracking pgtype.Bool
	err := row.Scan(&enabled_location_tracking)
	return enabled_location_tracking, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE settings 
SET 
    theme = COALESCE($2, theme),
    language = COALESCE($3, language),
    text_size = COALESCE($4, text_size),
    zoom_level = COALESCE($5, zoom_level),
    font_style = COALESCE($6, font_style),
    messages_allowance = COALESCE($7, messages_allowance),
    show_role_colors = COALESCE($8, show_role_colors),
    motion = COALESCE($9, motion),
    stickers_animation = COALESCE($10, stickers_animation),
    enabled_location_tracking = COALESCE($11, enabled_location_tracking),
    allow_city_stat_data_usage = COALESCE($12, allow_city_stat_data_usage),
    allow_data_personalization_usage = COALESCE($13, allow_data_personalization_usage),
    allow_in_app_rewards = COALESCE($14, allow_in_app_rewards),
    allow_data_analytics_and_performance = COALESCE($15, allow_data_analytics_and_performance),
    enable_in_app_notifications = COALESCE($16, enable_in_app_notifications),
    enable_sound_effects = COALESCE($17, enable_sound_effects),
    enable_vibration = COALESCE($18, enable_vibration),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, theme, language, text_size, zoom_level, font_style, messages_allowance, show_role_colors, motion, stickers_animation, enabled_location_tracking, allow_city_stat_data_usage, allow_data_personalization_usage, allow_in_app_rewards, allow_data_analytics_and_performance, enable_in_app_notifications, enable_sound_effects, enable_vibration, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	UserID                           string                `json:"user_id"`
	Theme                            NullTheme             `json:"theme"`
	Language                         NullLanguage          `json:"language"`
	TextSize                         NullTextSize          `json:"text_size"`
	ZoomLevel                        pgtype.Text           `json:"zoom_level"`
	FontStyle                        pgtype.Text           `json:"font_style"`
	MessagesAllowance                NullMessagesAllowance `json:"messages_allowance"`
	ShowRoleColors                   NullRoleColors        `json:"show_role_colors"`
	Motion                           NullMotion            `json:"motion"`
	StickersAnimation                NullStickersAnimation `json:"stickers_animation"`
	EnabledLocationTracking          pgtype.Bool           `json:"enabled_location_tracking"`
	AllowCityStatDataUsage           pgtype.Bool           `json:"allow_city_stat_data_usage"`
	AllowDataPersonalizationUsage    pgtype.Bool           `json:"allow_data_personalization_usage"`
	AllowInAppRewards                pgtype.Bool           `json:"allow_in_app_rewards"`
	AllowDataAnalyticsAndPerformance pgtype.Bool           `json:"allow_data_analytics_and_performance"`
	EnableInAppNotifications         pgtype.Bool           `json:"enable_in_app_notifications"`
	EnableSoundEffects               pgtype.Bool           `json:"enable_sound_effects"`
	EnableVibration                  pgtype.Bool           `json:"enable_vibration"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.TextSize,
		arg.ZoomLevel,
		arg.FontStyle,
		arg.MessagesAllowance,
		arg.ShowRoleColors,
		arg.Motion,
		arg.StickersAnimation,
		arg.EnabledLocationTracking,
		arg.AllowCityStatDataUsage,
		arg.AllowDataPersonalizationUsage,
		arg.AllowInAppRewards,
		arg.AllowDataAnalyticsAndPerformance,
		arg.EnableInAppNotifications,
		arg.EnableSoundEffects,
		arg.EnableVibration,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.TextSize,
		&i.ZoomLevel,
		&i.FontStyle,
		&i.MessagesAllowance,
		&i.ShowRoleColors,
		&i.Motion,
		&i.StickersAnimation,
		&i.EnabledLocationTracking,
		&i.AllowCityStatDataUsage,
		&i.AllowDataPersonalizationUsage,
		&i.AllowInAppRewards,
		&i.AllowDataAnalyticsAndPerformance,
		&i.EnableInAppNotifications,
		&i.EnableSoundEffects,
		&i.EnableVibration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
