// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, first_name, last_name, user_name, image_url, phone_number, role, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, email, first_name, last_name, user_name, image_url, phone_number, role, status, completed_tutorial, about_me, note, disable_account, delete_account, created_at, updated_at
`

type CreateUserParams struct {
	ID          string         `json:"id"`
	Email       string         `json:"email"`
	FirstName   pgtype.Text    `json:"first_name"`
	LastName    pgtype.Text    `json:"last_name"`
	UserName    pgtype.Text    `json:"user_name"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	PhoneNumber pgtype.Text    `json:"phone_number"`
	Role        NullUserRole   `json:"role"`
	Status      NullUserStatus `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UserName,
		arg.ImageUrl,
		arg.PhoneNumber,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserName,
		&i.ImageUrl,
		&i.PhoneNumber,
		&i.Role,
		&i.Status,
		&i.CompletedTutorial,
		&i.AboutMe,
		&i.Note,
		&i.DisableAccount,
		&i.DeleteAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, email, first_name, last_name, user_name, image_url, phone_number, role, status, completed_tutorial, about_me, note, disable_account, delete_account, created_at, updated_at FROM users WHERE id = $1
`

// sql/queries/users.sql
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserName,
		&i.ImageUrl,
		&i.PhoneNumber,
		&i.Role,
		&i.Status,
		&i.CompletedTutorial,
		&i.AboutMe,
		&i.Note,
		&i.DisableAccount,
		&i.DeleteAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, user_name, first_name, last_name, image_url
FROM users 
WHERE user_name ILIKE '%' || $2 || '%' 
AND id != $1
LIMIT 10
`
type SearchUsersParams struct {
	ID       string      `json:"id"`
	UserName pgtype.Text `json:"user_name"`
}

type SearchUsersRow struct {
	ID        string      `json:"id"`
	UserName  pgtype.Text `json:"user_name"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	ImageUrl  pgtype.Text `json:"image_url"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.ID, arg.UserName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    user_name = COALESCE($4, user_name),
    image_url = COALESCE($5, image_url),
    phone_number = COALESCE($6, phone_number),
    completed_tutorial = COALESCE($7, completed_tutorial),
    about_me = COALESCE($8, about_me),
    note = COALESCE($9, note),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, first_name, last_name, user_name, image_url, phone_number, role, status, completed_tutorial, about_me, note, disable_account, delete_account, created_at, updated_at
`

type UpdateUserParams struct {
	ID                string      `json:"id"`
	FirstName         pgtype.Text `json:"first_name"`
	LastName          pgtype.Text `json:"last_name"`
	UserName          pgtype.Text `json:"user_name"`
	ImageUrl          pgtype.Text `json:"image_url"`
	PhoneNumber       pgtype.Text `json:"phone_number"`
	CompletedTutorial pgtype.Bool `json:"completed_tutorial"`
	AboutMe           pgtype.Text `json:"about_me"`
	Note              pgtype.Text `json:"note"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.UserName,
		arg.ImageUrl,
		arg.PhoneNumber,
		arg.CompletedTutorial,
		arg.AboutMe,
		arg.Note,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.UserName,
		&i.ImageUrl,
		&i.PhoneNumber,
		&i.Role,
		&i.Status,
		&i.CompletedTutorial,
		&i.AboutMe,
		&i.Note,
		&i.DisableAccount,
		&i.DeleteAccount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
