// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: visited_streets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkVisitedStreetExists = `-- name: CheckVisitedStreetExists :one
SELECT COUNT(*) FROM visited_streets 
WHERE user_id = $1 AND session_id = $2 AND street_id = $3 AND entry_timestamp = $4
`

type CheckVisitedStreetExistsParams struct {
	UserID         string `json:"user_id"`
	SessionID      string `json:"session_id"`
	StreetID       string `json:"street_id"`
	EntryTimestamp int64  `json:"entry_timestamp"`
}

func (q *Queries) CheckVisitedStreetExists(ctx context.Context, arg CheckVisitedStreetExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkVisitedStreetExists,
		arg.UserID,
		arg.SessionID,
		arg.StreetID,
		arg.EntryTimestamp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVisitedStreet = `-- name: CreateVisitedStreet :one
INSERT INTO visited_streets (
    user_id, session_id, street_id, street_name, entry_timestamp,
    exit_timestamp, duration_seconds, entry_latitude, entry_longitude
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, session_id, street_id, street_name, entry_timestamp, exit_timestamp, duration_seconds, entry_latitude, entry_longitude, created_at
`

type CreateVisitedStreetParams struct {
	UserID          string         `json:"user_id"`
	SessionID       string         `json:"session_id"`
	StreetID        string         `json:"street_id"`
	StreetName      string         `json:"street_name"`
	EntryTimestamp  int64          `json:"entry_timestamp"`
	ExitTimestamp   pgtype.Int8    `json:"exit_timestamp"`
	DurationSeconds pgtype.Int4    `json:"duration_seconds"`
	EntryLatitude   pgtype.Numeric `json:"entry_latitude"`
	EntryLongitude  pgtype.Numeric `json:"entry_longitude"`
}

func (q *Queries) CreateVisitedStreet(ctx context.Context, arg CreateVisitedStreetParams) (VisitedStreet, error) {
	row := q.db.QueryRow(ctx, createVisitedStreet,
		arg.UserID,
		arg.SessionID,
		arg.StreetID,
		arg.StreetName,
		arg.EntryTimestamp,
		arg.ExitTimestamp,
		arg.DurationSeconds,
		arg.EntryLatitude,
		arg.EntryLongitude,
	)
	var i VisitedStreet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.StreetID,
		&i.StreetName,
		&i.EntryTimestamp,
		&i.ExitTimestamp,
		&i.DurationSeconds,
		&i.EntryLatitude,
		&i.EntryLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const getVisitedStreets = `-- name: GetVisitedStreets :many

SELECT id, user_id, session_id, street_id, street_name, entry_timestamp, exit_timestamp, duration_seconds, entry_latitude, entry_longitude, created_at FROM visited_streets 
WHERE user_id = $1
ORDER BY entry_timestamp DESC
`

// sql/queries/visited_streets.sql
func (q *Queries) GetVisitedStreets(ctx context.Context, userID string) ([]VisitedStreet, error) {
	rows, err := q.db.Query(ctx, getVisitedStreets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisitedStreet
	for rows.Next() {
		var i VisitedStreet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.StreetID,
			&i.StreetName,
			&i.EntryTimestamp,
			&i.ExitTimestamp,
			&i.DurationSeconds,
			&i.EntryLatitude,
			&i.EntryLongitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitedStreetsBySession = `-- name: GetVisitedStreetsBySession :many
SELECT id, user_id, session_id, street_id, street_name, entry_timestamp, exit_timestamp, duration_seconds, entry_latitude, entry_longitude, created_at FROM visited_streets 
WHERE user_id = $1 AND session_id = $2
ORDER BY entry_timestamp ASC
`

type GetVisitedStreetsBySessionParams struct {
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetVisitedStreetsBySession(ctx context.Context, arg GetVisitedStreetsBySessionParams) ([]VisitedStreet, error) {
	rows, err := q.db.Query(ctx, getVisitedStreetsBySession, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisitedStreet
	for rows.Next() {
		var i VisitedStreet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.StreetID,
			&i.StreetName,
			&i.EntryTimestamp,
			&i.ExitTimestamp,
			&i.DurationSeconds,
			&i.EntryLatitude,
			&i.EntryLongitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
